### ISSUE TITLE
Pillow Image no longer supports fromstring

### ISSUE THREAD

**Issue by pi-cjm** [jaraco/jaraco.video#8]
Just upgraded to 2.0 and got this:

```
C:\Users\cjm\Documents\Capture>python -m jaraco.video.capture
# Generating comtypes.gen._24BC6711_3881_420F_8299_34DA1026D31E_0_1_0
# Generating comtypes.gen._78530B68_61F9_11D2_8CAD_00A024580902_0_1_0
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\lib\site-packages\jaraco\video\capture.py", line 368, in <module>
    save_frame()
  File "C:\Python27\lib\site-packages\jaraco\video\capture.py", line 365, in save_frame
    d.save_snapshot(filename, timestamp='simple')
  File "C:\Python27\lib\site-packages\jaraco\video\capture.py", line 347, in save_snapshot
    self.get_image(timestamp, font, textpos).save(filename, **kwargs)
  File "C:\Python27\lib\site-packages\jaraco\video\capture.py", line 283, in get_image
    img = PIL.Image.fromstring('RGB', dimensions, buffer, 'raw', 'BGR', 0, -1)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2063, in fromstring
    "Please call frombytes() instead.")
Exception: fromstring() has been removed. Please call frombytes() instead.
```

Using Pillow 3.1.0

**Comment by jaraco** [comment]
Fixed in 2.1.1.
